<?php

return [
    'default_amount' => 200,
    'default_batch_size' => 50,
    'exam' => 'Revalida',
    'phase' => 'first',
    'origin' => 'ai_seeded',
    'status' => 'draft',
    'difficulty_mix' => [
        'Fácil' => 10,
        'Média' => 60,
        'Difícil' => 30,
    ],
    'style_mix' => [
        'caso_clinico' => 70,
        'aps_sus_preventiva' => 20,
        'conceito_direto' => 10,
    ],
    'style_angles' => [
        'caso_clinico' => [
            'diagnóstico principal',
            'conduta inicial no SUS',
            'exame complementar mais útil',
            'estratificação de gravidade',
            'tratamento ambulatorial ou hospitalar',
            'seguimento após estabilização',
        ],
        'aps_sus_preventiva' => [
            'abordagem na atenção primária',
            'prevenção e rastreamento',
            'vacinação ou quimioprofilaxia quando aplicável',
            'notificação ou vigilância epidemiológica',
            'fluxo assistencial no SUS',
            'educação em saúde e longitudinalidade',
        ],
        'conceito_direto' => [
            'critério diagnóstico',
            'conceito-chave de prova',
            'indicação clássica',
            'contraindicação ou precaução',
            'interpretação objetiva de achado',
            'definição operacional',
        ],
    ],
    'areas' => [
        'clinica_medica' => [
            'label' => 'Clínica Médica',
            'aliases' => ['clinica', 'clinica medica', 'clínica', 'clínica médica', 'cm', 'clinica_medica'],
            'weight' => 0.28,
            'topics' => [
                'Diabetes mellitus tipo 2 com doença cardiovascular aterosclerótica',
                'Cetoacidose diabética e estado hiperosmolar',
                'Síndrome coronariana aguda',
                'Insuficiência cardíaca descompensada',
                'Doença pulmonar obstrutiva crônica exacerbada',
                'Asma aguda no adulto',
                'Sepse e choque séptico',
                'Acidente vascular cerebral isquêmico',
                'Hipertensão arterial sistêmica resistente',
                'Dengue com sinais de alarme',
                'Tuberculose pulmonar',
                'Infecção pelo HIV e profilaxias',
                'Insuficiência renal aguda',
                'Anemia ferropriva e investigação etiológica',
                'Cirrose hepática e complicações',
                'Tireotoxicose e hipotireoidismo',
                'Síndrome nefrótica e síndrome nefrítica',
                'Doença ulcerosa péptica e hemorragia digestiva alta',
            ],
        ],
        'go' => [
            'label' => 'GO',
            'aliases' => ['go', 'gineco', 'ginecologia', 'obstetricia', 'obstetrícia', 'gineco obstetricia', 'gineco/obstetricia'],
            'weight' => 0.18,
            'topics' => [
                'Pré-eclâmpsia com sinais de gravidade',
                'Eclâmpsia e estabilização materna',
                'Hemorragia pós-parto',
                'Pré-natal de baixo risco',
                'Sífilis gestacional',
                'Diabetes mellitus gestacional',
                'Trabalho de parto prematuro',
                'Placenta prévia e descolamento prematuro de placenta',
                'Abortamento e suas condutas',
                'Sangramento uterino anormal',
                'Rastreamento do câncer do colo do útero',
                'Sangramento pós-menopausa',
                'Infecção urinária na gestação',
                'Planejamento reprodutivo e contracepção',
                'Aleitamento materno e puerpério',
                'Violência sexual e profilaxias',
            ],
        ],
        'pediatria' => [
            'label' => 'Pediatria',
            'aliases' => ['pediatria', 'ped'],
            'weight' => 0.16,
            'topics' => [
                'Desidratação por diarreia aguda',
                'Bronquiolite viral aguda',
                'Pneumonia adquirida na comunidade',
                'Asma na infância',
                'Sepse neonatal',
                'Puericultura e desenvolvimento neuropsicomotor',
                'Calendário vacinal da criança',
                'Convulsão febril',
                'Infecção do trato urinário na infância',
                'Icterícia neonatal',
                'Anemia ferropriva',
                'Meningite bacteriana',
                'Desnutrição energético-proteica',
                'Cardiopatias congênitas e triagem neonatal',
                'Exantemas na infância',
                'Manejo da febre sem sinais de gravidade',
            ],
        ],
        'cirurgia' => [
            'label' => 'Cirurgia',
            'aliases' => ['cirurgia', 'cir', 'cx'],
            'weight' => 0.14,
            'topics' => [
                'Apendicite aguda',
                'Colecistite aguda',
                'Pancreatite aguda',
                'Trauma e abordagem ABCDE',
                'Obstrução intestinal',
                'Perfuração de víscera oca',
                'Hérnia encarcerada e estrangulada',
                'Queimaduras e reposição volêmica',
                'Pneumotórax hipertensivo',
                'Pé diabético infectado',
                'Complicações pós-operatórias imediatas',
                'Escroto agudo',
                'Tromboprofilaxia no perioperatório',
                'Hemorragia digestiva baixa com indicação cirúrgica',
                'Abdome agudo inflamatório',
                'Trauma abdominal fechado',
            ],
        ],
        'preventiva_sus' => [
            'label' => 'Preventiva/SUS',
            'aliases' => ['preventiva', 'sus', 'preventiva/sus', 'mfc', 'saude coletiva', 'saúde coletiva'],
            'weight' => 0.18,
            'topics' => [
                'Atributos da atenção primária à saúde',
                'Linhas de cuidado na APS para hipertensão e diabetes',
                'Notificação compulsória',
                'Vigilância epidemiológica e investigação de surtos',
                'Calendário vacinal do adulto e do idoso',
                'Rastreamento populacional e prevenção quaternária',
                'Tuberculose: busca de contatos e tratamento diretamente observado',
                'Hanseníase na atenção primária',
                'Infecções sexualmente transmissíveis e prevenção combinada',
                'Saúde mental na APS',
                'Arboviroses e medidas de controle',
                'Cuidados paliativos e comunicação de más notícias no SUS',
                'Saúde do trabalhador',
                'Indicadores de saúde e planejamento local',
                'Segurança do paciente e eventos adversos',
                'Ética, confidencialidade e autonomia',
            ],
        ],
    ],
];
